### ISSUE TITLE
syntax error line 51 ?

### ISSUE THREAD

**Issue by tangawk** [niggo372/libinput-gestures#1]
New to github so not sure if this is the best way to feedback, apologies if not.

I'm on : Fedora 27 (4.17.9-100.fc27.x86_64 #1 SMP Mon Jul 23 22:35:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

Getting this error when running sh mousemapper.sh as sudo

line 51: syntax error near unexpected token `<'
line 51: `    done < <(stdbuf -oL libinput debug-events --device ${device} & )'

My bash script is not up to debugging this myself - tried removing one of the "<" signs in case of a typo but no joy.

Getting this working would be great for me.

Thanks Adrian

**Comment by shrugal** [comment]
It's probably a bit late anyway, but if you still need help you have to ask in the forked project: https://github.com/mathportillo/wayland-mouse-mapper
